export const MOCK_RECIPES = {
  results: [
    {
      id: 633752,
      title: 'Baked Ravioli & Meat Sauce',
      image: 'https://img.spoonacular.com/recipes/633752-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 1504227,
      title: 'Easy Italian Meatballs',
      image: 'https://img.spoonacular.com/recipes/1504227-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 651381,
      title: 'Meaty One Dish Risotto',
      image: 'https://img.spoonacular.com/recipes/651381-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 648176,
      title: 'Italian Meatloaf with Hard Boiled Eggs',
      image: 'https://img.spoonacular.com/recipes/648176-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 651965,
      title: 'Mini Meatball & Ravioli Soup With Garlic Croutons',
      image: 'https://img.spoonacular.com/recipes/651965-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 654125,
      title: 'Osso Buco',
      image: 'https://img.spoonacular.com/recipes/654125-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 680975,
      title: 'BLT Pizza',
      image: 'https://img.spoonacular.com/recipes/680975-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 716300,
      title: 'Plantain Pizza',
      image: 'https://img.spoonacular.com/recipes/716300-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 658024,
      title: 'Minestrone Soup',
      image: 'https://img.spoonacular.com/recipes/658024-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 659358,
      title: 'Sausage Calzone',
      image: 'https://img.spoonacular.com/recipes/659358-312x231.jpg',
      imageType: 'jpg',
    },
  ],
  offset: 0,
  number: 10,
  totalResults: 72,
};

export const MOCK_DETAILS = {
  id: 633752,
  image: 'https://img.spoonacular.com/recipes/633752-556x370.jpg',
  imageType: 'jpg',
  title: 'Baked Ravioli & Meat Sauce',
  readyInMinutes: 45,
  servings: 8,
  sourceUrl:
    'https://www.foodista.com/recipe/PKJT7TDN/baked-ravioli-meat-sauce',
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 18,
  gaps: 'no',
  preparationMinutes: null,
  cookingMinutes: null,
  aggregateLikes: 1,
  healthScore: 9,
  creditsText: 'foodista.com',
  license: null,
  sourceName: 'foodista.com',
  pricePerServing: 207.12,
  extendedIngredients: [
    {
      id: 10023572,
      aisle: 'Meat',
      image: 'fresh-ground-beef.jpg',
      consistency: 'SOLID',
      name: 'ground beef',
      nameClean: 'ground chuck',
      original: '1 pound of Ground Beef (80-85%%)',
      originalName: 'Ground Beef (80-85%%)',
      amount: 1,
      unit: 'pound',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 11333,
      aisle: 'Produce',
      image: 'green-pepper.jpg',
      consistency: 'SOLID',
      name: 'bell pepper',
      nameClean: 'green pepper',
      original: '1 Green Pepper, thinly sliced and cut into 1-inch long strips',
      originalName:
        'Green Pepper, thinly sliced and cut into 1-inch long strips',
      amount: 1,
      unit: '',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 10511282,
      aisle: 'Produce',
      image: 'brown-onion.png',
      consistency: 'SOLID',
      name: 'onion',
      nameClean: 'yellow onion',
      original: '1 large Yellow Onion, diced',
      originalName: 'Yellow Onion, diced',
      amount: 1,
      unit: 'large',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 11215,
      aisle: 'Produce',
      image: 'garlic.png',
      consistency: 'SOLID',
      name: 'garlic',
      nameClean: 'garlic',
      original: '5 large cloves Garlic, minced',
      originalName: 'Garlic, minced',
      amount: 5,
      unit: 'large cloves',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 4053,
      aisle: 'Oil, Vinegar, Salad Dressing',
      image: 'olive-oil.jpg',
      consistency: 'LIQUID',
      name: 'olive oil',
      nameClean: 'olive oil',
      original: '3 tablespoons Olive Oil',
      originalName: 'Olive Oil',
      amount: 3,
      unit: 'tablespoons',
      meta: [],
      measures: [Object],
    },
    {
      id: 10011693,
      aisle: 'Canned and Jarred',
      image: 'tomatoes-canned.png',
      consistency: 'SOLID',
      name: 'tomato paste',
      nameClean: 'canned tomatoes',
      original: '1 ounce can tomato paste, 6',
      originalName: 'tomato paste, 6',
      amount: 1,
      unit: 'ounce',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 1022027,
      aisle: 'Spices and Seasonings',
      image: 'dried-herbs.png',
      consistency: 'SOLID',
      name: 'seasoning',
      nameClean: 'italian seasoning',
      original:
        "2 teaspoons tablespoons Italian Seasoning (If you don't have the mix use 1 each of",
      originalName:
        "tablespoons Italian Seasoning (If you don't have the mix use 1 each of",
      amount: 2,
      unit: 'teaspoons',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 19335,
      aisle: 'Baking',
      image: 'sugar-in-bowl.png',
      consistency: 'SOLID',
      name: 'sugar',
      nameClean: 'sugar',
      original: '1 teaspoon Sugar',
      originalName: 'Sugar',
      amount: 1,
      unit: 'teaspoon',
      meta: [],
      measures: [Object],
    },
    {
      id: 1082047,
      aisle: 'Spices and Seasonings',
      image: 'salt.jpg',
      consistency: 'SOLID',
      name: 'kosher salt',
      nameClean: 'kosher salt',
      original: '1 teaspoon Sea or Kosher salt',
      originalName: 'Sea or Kosher salt',
      amount: 1,
      unit: 'teaspoon',
      meta: [],
      measures: [Object],
    },
    {
      id: 1002030,
      aisle: 'Spices and Seasonings',
      image: 'pepper.jpg',
      consistency: 'SOLID',
      name: 'cracked pepper',
      nameClean: 'black pepper',
      original: 'Fresh cracked Pepper',
      originalName: 'Fresh cracked Pepper',
      amount: 8,
      unit: 'servings',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 2004,
      aisle: 'Produce',
      image: 'bay-leaves.jpg',
      consistency: 'SOLID',
      name: 'bay leaves',
      nameClean: 'bay leaves',
      original: '2 bay leaves',
      originalName: 'bay leaves',
      amount: 2,
      unit: '',
      meta: [],
      measures: [Object],
    },
    {
      id: 11693,
      aisle: 'Canned and Jarred',
      image: 'tomatoes-canned.png',
      consistency: 'SOLID',
      name: 'canned tomatoes',
      nameClean: 'crushed tomatoes',
      original: '28 ounces can of crushed tomatoes',
      originalName: 'crushed tomatoes',
      amount: 28,
      unit: 'ounces',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 1001026,
      aisle: 'Cheese',
      image: 'shredded-cheese-white.jpg',
      consistency: 'SOLID',
      name: 'mozzarella cheese',
      nameClean: 'shredded mozzarella',
      original: '2 cups Mozzarella Cheese, shredded',
      originalName: 'Mozzarella Cheese, shredded',
      amount: 2,
      unit: 'cups',
      meta: [Array],
      measures: [Object],
    },
    {
      id: 93832,
      aisle: 'Frozen',
      image: 'ravioli.png',
      consistency: 'SOLID',
      name: 'use',
      nameClean: 'cheese ravioli',
      original: '26 ounces Cheese Ravioli, frozen, or fresh, use good quality',
      originalName: 'Cheese Ravioli, frozen, or fresh, use good quality',
      amount: 26,
      unit: 'ounces',
      meta: [Array],
      measures: [Object],
    },
  ],
  summary:
    'Baked Ravioli & Meat Sauce is a Mediterranean main course. For <b>$2.07 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains about <b>32g of protein</b>, <b>34g of fat</b>, and a total of <b>631 calories</b>. This recipe serves 8. It is brought to you by Foodista. 1 person were glad they tried this recipe. Head to the store and pick up tomato paste, sugar, bay leaves, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 42%</b>. Try <a href="https://spoonacular.com/recipes/quick-and-easy-baked-ravioli-with-creamy-meat-sauce-621710">Quick and Easy Baked Ravioli with Creamy Meat Sauce</a>, <a href="https://spoonacular.com/recipes/baked-penne-with-meat-sauce-139066">Baked Penne With Meat Sauce</a>, and <a href="https://spoonacular.com/recipes/baked-linguine-with-meat-sauce-1283813">Baked Linguine with Meat Sauce</a> for similar recipes.',
  cuisines: ['Mediterranean', 'Italian', 'European'],
  dishTypes: ['side dish', 'lunch', 'main course', 'main dish', 'dinner'],
  diets: [],
  occasions: [],
  instructions:
    'Brown the beef and the pepper, onion and garlic in olive oil in a large, heavy bottomed sauce pan.\n' +
    'When browned add the tomato paste, Italian seasonings, sugar, salt, pepper, and bay leaves. Let cook for a few minutes until the tomato paste is heated through.\n' +
    'Add the crushed tomatoes and a half of the tomato paste can full of water. Simmer for 25-30 minutes. Taste and re-season halfway through with salt, pepper and herbs if needed and again before serving.\n' +
    'While the sauce is simmering cook the ravioli just until they begin to rise to the top and float. You do not need to cook them all the way through. Drain and toss with a tablespoon of butter or olive oil.\n' +
    'Preheat oven to 400 degrees. Remove bay leaves from sauce. Toss a liberal amount of sauce with ravioli. Reserve any excess sauce for serving.\n' +
    'Pour into a greased 9x13 casserole pan. Sprinkle top with mozzarella. Bake about 25 minutes or until bubbly.\n' +
    'Best served with fresh shredded Parmesan, garlic bread, extra sauce and a green salad.',
  analyzedInstructions: [{ name: '', steps: [Array] }],
  originalId: null,
  spoonacularScore: 50.98750686645508,
  spoonacularSourceUrl:
    'https://spoonacular.com/baked-ravioli-meat-sauce-633752',
};
